### ISSUE TITLE
Reactpoll Timer not ending

### ISSUE THREAD

**Issue by Skyridr** [ptoast/FlapJack-Cogs#102]
For some reason, regardless what time you use (5 seconds, 60, etc), the rpoll won't end. Poll is being created just fine, but the bot won't close the poll on the desired timer you use. No errors appear either.

**Comment by Skyridr** [comment]
I've updated @aikaterna but it still didn't work for me. Restarted the bot & unloaded/reloaded the cog just in case, and the timer still seems to be stuck. Any other previous rpoll that were made are not closed either.  

Also made sure if the new cog update matched the one I have, and according to the lovely text difference 

> The two files are identical

**Comment by aikaterna** [comment]
Can I have a copy of your settings.json then?

**Comment by Skyridr** [comment]
Sorry, forgot to reply.

Do you refer to the settings.json in core directory or the CogManager directory?

**Comment by aikaterna** [comment]
The settings.json for the cog, which is in the data directory/CogManager dir.

**Comment by Skyridr** [comment]
```
{
    "2938473984732" : {
        "GLOBAL" : {
            "paths" : [
                "/home/skyrider/discord/redv3/cogs/ESF"
            ]
        }
    }
}
```
cogs/ESF is something I added a long time ago when I first started using V3 and I am no longer using it. Nothing really broke cog wise, so I forgot I even put it there.

**Comment by aikaterna** [comment]
That seems like a bot level settings.json and not the cog's file.

**Comment by Skyridr** [comment]
Guess the reason why I couldn't find it is because I'm using mongodb. I noticed when I checked the reactPoll.Global polls, that multiple polls are listed but simply not ending:

![image](https://user-images.githubusercontent.com/6794064/68415452-b0209600-0192-11ea-999f-20243dd8ee2a.png)

Anything in particular that you wanted? As I assume the settings.json would (if saved by file) contain the info from the above image?

Here's a copy:

https://pastebin.com/PRJcdYNK

**Comment by aikaterna** [comment]
I'm closing this again as it seemed like it might have been mongo related, and we also did some talking outside of this issue, in the Cog Server. Reactpoll was also changed up a bit recently with a large refactor Trusty did, so I doubt this is going to crop up again... and if it does it will be related to the new code.
