### ISSUE TITLE
[React Poll] Suggestion

### ISSUE THREAD

**Issue by Menteroth** [ptoast/FlapJack-Cogs#105]
Would it be possible to add to see duration of a poll in other format than just a bunch of seconds?
Because you can use seconds/hours when you create a poll. Haven't tried days though. And minutes doesn't work. But I guess seconds cover that. But could be an option too.

Also a cancel poll option would be great if you make a mistake when creating it for instance.

**Comment by aikaterna** [comment]
Hi Menteroth, you can find this new option in reactpoll's update from Trusty.
