### ISSUE TITLE
someone pls help

### ISSUE THREAD

**Issue by kpopdev** [ptoast/FlapJack-Cogs#111]
i got this error when i load smartreact cog 
"\New folder\\Red-DiscordBot\\cogs\\smartreact.py', 56, 56, '        msg = f"Smar
t Reactions for {ctx.guild.name}:\\n"\n'))

**Comment by aikaterna** [comment]
Please show the entire error. Feel free to link to a pastebin, hastebin, or other service to link a long amount of text, if needed.

**Comment by flaree** [comment]
v2 is EOL, please install v3 @ https://docs.discord.red/en/stable

**Comment by aikaterna** [comment]
Turns out they were installing the v3 version on a v2 bot.
