### ISSUE TITLE
Error when starting a new poll with reactpoll

### ISSUE THREAD

**Issue by bencerda1** [ptoast/FlapJack-Cogs#122]
Hi there, I've just installed your reactpoll cog and am encountering errors when attempting to start a new poll.

Attached is the traceback provided through the traceback command
[error.txt](https://github.com/flapjax/FlapJack-Cogs/files/5587831/error.txt)

**Comment by Menteroth** [comment]
Just paste the error in your post. Sometimes they are on mobile and that would be easier then. Can surround the text with ``` for codeblock here as well.

**Comment by aikaterna** [comment]
You need to enable intents on your bot. This also leads me to believe you are not up to date with Red. 

See https://docs.discord.red/en/stable/update_red.html amd https://docs.discord.red/en/stable/bot_application_guide.html#enabling-privileged-intents
