### ISSUE TITLE
smartreact is not working after I install it.

### ISSUE THREAD

**Issue by SysAdmin74** [ptoast/FlapJack-Cogs#133]
I am new to redbot discord. I couldn't find the command to use it in the help section. Sorry to opening new issues here because I don't really know where to ask about this.

The cog is loaded already, no command available

**Comment by aikaterna** [comment]
`[p]help SmartReact` where [p] is your prefix that you chose to use for your bot. Alternatively you could use [p]help and look through the list for the SmartReact header. You also must run these commands in a Discord server as smartreact doesn't work in DMs and commands for it won't show up in help if you try. If you join the main Red support server at discord.gg/red, there's a link in the welcome channel for the 3rd party cog Discord server where a lot of cog authors provide help for their cogs.

**Comment by SysAdmin74** [comment]
Ohh thank you so much. I have been setting things up in DM only. Don't know why the bot now only msg in dm ;-;
Sorry for opening a issues
